### ISSUE TITLE
Produces wrong output compared to github math

### ISSUE THREAD

**Issue by snimavat** [micromark/micromark-extension-math#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

    "micromark-extension-math": "^2.1.2",

### Steps to reproduce

This is what I have 

```
const mdToHtml = (md) => {
   const result = micromark(md, {
      extensions: [gfm(), math()],
      htmlExtensions: [gfmHtml(), mathHtml()]
   })
   return result
}
```

For the input 

```
$\left[\mathrm{ML}^2 \mathrm{~T}^{-2} \mathrm{~K}\right]$
```

It generates out put which contains extra ```[ML2 T−2 K−1]``` right after the equation

**See screenshot for generated output**
<img width="382" alt="Screenshot 2023-06-07 at 10 46 57 PM" src="https://github.com/micromark/micromark-extension-math/assets/623295/a44cd86b-b2bc-4963-886f-19e666b4d24f">

### Expected behavior

Expect it to generate only math formula without extra output

### Actual behavior

Generates exra output

**Comment by wooorm** [comment]
Read the readme. Use CSS. https://github.com/micromark/micromark-extension-math#css

**Comment by snimavat** [comment]
Sorry for missing that - i will check and update. Thanks
