### ISSUE TITLE
"$20,000 and $30,000" should’t parse as math (if remark-math and micromark-extension-math follows Pandoc as remark-math 3.0 did)

### ISSUE THREAD

**Issue by seiyab** [micromark/micromark-extension-math#6]
Older remark-math handled it same as pandoc: https://github.com/remarkjs/remark-math/pull/35. I consider this a regression.

### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-math 6.0.0

### Link to runnable example
[Codesandbox](
https://codesandbox.io/p/sandbox/divine-wind-mrfzt5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsir4bi900062e658bw6cmsg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsir4bi900022e65zage695n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsir4bi900032e650myk5xsx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsir4bi900052e65kbdsiov2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsir4bi900022e65zage695n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsir4bi900012e65uru17vda%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsir4bi900022e65zage695n%2522%252C%2522activeTabId%2522%253A%2522clsir4bi900012e65uru17vda%2522%257D%252C%2522clsir4bi900052e65kbdsiov2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsir4bi900042e658yy5wc0r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsir4bi900052e65kbdsiov2%2522%252C%2522activeTabId%2522%253A%2522clsir4bi900042e658yy5wc0r%2522%257D%252C%2522clsir4bi900032e650myk5xsx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsir4bi900032e650myk5xsx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A24.46745562130178%257D)

### Steps to reproduce

[Codesandbox](https://codesandbox.io/p/sandbox/divine-wind-mrfzt5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsir4bi900062e658bw6cmsg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsir4bi900022e65zage695n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsir4bi900032e650myk5xsx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsir4bi900052e65kbdsiov2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsir4bi900022e65zage695n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsir4bi900012e65uru17vda%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsir4bi900022e65zage695n%2522%252C%2522activeTabId%2522%253A%2522clsir4bi900012e65uru17vda%2522%257D%252C%2522clsir4bi900052e65kbdsiov2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsir4bi900042e658yy5wc0r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsir4bi900052e65kbdsiov2%2522%252C%2522activeTabId%2522%253A%2522clsir4bi900042e658yy5wc0r%2522%257D%252C%2522clsir4bi900032e650myk5xsx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsir4bi900032e650myk5xsx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A24.46745562130178%257D)

```js
import remarkParse from "remark-parse";
import { unified } from "unified";
import remarkMath from "remark-math";

const sourceMarkdown = `$20,000 and $30,000`;

document.getElementById("source").textContent = sourceMarkdown;

const processor = unified().use(remarkParse).use(remarkMath);

processor
  .run(processor.parse(sourceMarkdown))
  .then((file) => {
    document.getElementById("result").textContent = JSON.stringify(
      file,
      null,
      2
    );
  })
  .catch((err) => (document.getElementById("error").textContent = err));
```

### Expected behavior

It shouldn't parse as math.

### Actual behavior

parses as inline math.
```json
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "inlineMath",
          "value": "20,000 and ",
          "data": {
            "hName": "code",
            "hProperties": {
              "className": [
                "language-math",
                "math-inline"
              ]
            },
            "hChildren": [
              {
                "type": "text",
                "value": "20,000 and "
              }
            ]
          },
          "position": {
            "start": {
              "line": 1,
              "column": 1,
              "offset": 0
            },
            "end": {
              "line": 1,
              "column": 14,
              "offset": 13
            }
          }
        },
        {
          "type": "text",
          "value": "30,000",
          "position": {
            "start": {
              "line": 1,
              "column": 14,
              "offset": 13
            },
            "end": {
              "line": 1,
              "column": 20,
              "offset": 19
            }
          }
        }
      ],
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 1,
          "column": 20,
          "offset": 19
        }
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1,
      "offset": 0
    },
    "end": {
      "line": 1,
      "column": 20,
      "offset": 19
    }
  }
}
```

**Comment by wooorm** [comment]
Hi

The behavior is intended. Pandoc is not a reference. How code works in CommonMark is a reference.

```markdown
`20,000 and `30,000
```

`20,000 and `30,000

You can escape dollars and backticks in markdown if you want:

```markdown
\`20,000 and `30,000
```

\`20,000 and `30,000

You can also turn off [`singleDollarTextMath`](https://github.com/micromark/micromark-extension-math#options) in this extension. This is what I would recommend to everyone. With that, math is unlikely to interfere with regular text. That is also how I implemented syntax highlighting, which is used in places where math may or may not work, such as right here:

```markdown
$math?$

$$math?$$
```

**Comment by wooorm** [comment]
The PR you reference also says what I say now. Pandoc is not a reference. https://github.com/remarkjs/remark-math/pull/35

**Comment by seiyab** [comment]
Thank you for your response. I understand. I'm working on Prettier and will suggest turning off `singleDollarTextMath` with breaking change or having our own tokenizer.
