### ISSUE TITLE
Can't escape `$` in math

### ISSUE THREAD

**Issue by nvlang** [micromark/micromark-extension-math#7]
### Initial checklist

- [x] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-extension-math@3.0.0

### Link to runnable example

https://github.com/nvlang/micromark-extension-math-bug

### Steps to reproduce

1. Clone https://github.com/nvlang/micromark-extension-math-bug
2. Run `npm i` (or `pnpm i`)
3. Run `node index.js`

### Expected behavior

`$ a \$ b $` should be parsed as an inline math node with
content ` a \$ b `.

### Actual behavior

`$ a \$ b $` is parsed as follows:
- `$ a \$`: math node with content `a \`
- `b $`: text node with content `b $`

### Runtime

Node v16

### Package manager

pnpm

### OS

macOS

---
### Edit

I just looked at this package's unit tests and noticed that this seems to be the expected behavior. I'm guessing the idea is to replicate the behavior from backticks. I suppose that this makes this not a bug report, but rather a matter of personal preference. However, I do believe that there is an argument in favor of the behavior I expected: it mirrors the behavior inside TeX documents.

I understand that there are advantages to having `$` behave like backticks; the main one that comes to mind is the ability to have math within text within math, i.e., `$$\text{$x$}$$` $\text{$x$}$. However, that behavior is still reconcilable with the behavior I expected.

**Comment by wooorm** [comment]
Right, you already answered this yourself. This is intended behavior. It is documented clearly: https://github.com/micromark/micromark-extension-math#syntax.

People probably know how code works in markdown. Or if they don’t, but then they can learn it, and it applies to both code and math.

I *love* not having to use escapes in code (and math). And it annoys me to have to do it in HTML.

You can use `$$a $ b$$` for your case.
