### ISSUE TITLE
Support the \( \[ formula syntax.

### ISSUE THREAD

**Issue by xl0** [micromark/micromark-extension-math#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

New OpenAI models such as `gpt-4o` and `o1` will output formulas for rendering with the \\\( \\\[ syntax by default:

User: `What is the formula for the volume of a sphere?`
Assistant:
```
The formula for the volume of a sphere is given by:

\[ V = \frac{4}{3} \pi r^3 \]

where \( V \) is the volume and \( r \) is the radius of the sphere.
```

It would be great to be able to parse this variant with micromark without having to resort to `.replace()`. 

Related: https://github.com/remarkjs/remark-math/issues/39

### Solution

- Parse the \\( \\[ syntax as expected.
- Add an Option to enable it.

### Alternatives

Do nothing

**Comment by wooorm** [comment]
Same answer as https://github.com/remarkjs/remark-math/issues/39#issuecomment-612572069.

The main alternative to adding every flavor that every tool comes up with in one package, is to have different packages for different things. We’ve mentioned this several times, see e.g. https://github.com/remarkjs/remark-math/issues/39#issuecomment-612572749.
I don’t have to do all the work. People can do things too?

You can also ask llms to do things, such as follow a particular style, in their output?
